// <auto-generated />
using System;
using BookManagementApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagementApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260715112517_AddBookExcerpts")]
    partial class AddBookExcerpts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.ProfileFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PriceInStones")
                        .HasColumnType("int");

                    b.Property<int>("RequiredBookCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProfileFrames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Doğanın dinginliği profilinde.",
                            IconEmoji = "🌿",
                            ImageUrl = "/images/frames/emerald.png",
                            Name = "Zümrüt Bahçesi",
                            PriceInStones = 100,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Her sayfa yeni bir ufuk.",
                            IconEmoji = "🌅",
                            ImageUrl = "/images/frames/sunset.png",
                            Name = "Gün Batımı",
                            PriceInStones = 120,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soğukkanlı okurların tercihi.",
                            IconEmoji = "❄️",
                            ImageUrl = "/images/frames/ice.png",
                            Name = "Buz Kristali",
                            PriceInStones = 150,
                            RequiredBookCount = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Asırlık kütüphanelerin ruhu.",
                            IconEmoji = "📜",
                            ImageUrl = "/images/frames/ancient.png",
                            Name = "Kadim Bilgelik",
                            PriceInStones = 250,
                            RequiredBookCount = 10
                        },
                        new
                        {
                            Id = 5,
                            Description = "Altın işlemeli mor ihtişam.",
                            IconEmoji = "💜",
                            ImageUrl = "/images/frames/royal.png",
                            Name = "Kraliyet Asaleti",
                            PriceInStones = 300,
                            RequiredBookCount = 15
                        },
                        new
                        {
                            Id = 6,
                            Description = "Geceleri parlayan dijital aura.",
                            IconEmoji = "🔮",
                            ImageUrl = "/images/frames/neon.png",
                            Name = "Siber Neon",
                            PriceInStones = 350,
                            RequiredBookCount = 20
                        },
                        new
                        {
                            Id = 7,
                            Description = "Parlayan saf altın ışıltısı.",
                            IconEmoji = "🥇",
                            ImageUrl = "/images/frames/gold.png",
                            Name = "Kraliyet Altını",
                            PriceInStones = 500,
                            RequiredBookCount = 30
                        },
                        new
                        {
                            Id = 8,
                            Description = "Kıvılcımlar saçan okuma tutkusu.",
                            IconEmoji = "🔥",
                            ImageUrl = "/images/frames/fire.png",
                            Name = "Cehennem Alevi",
                            PriceInStones = 600,
                            RequiredBookCount = 40
                        },
                        new
                        {
                            Id = 9,
                            Description = "Karanlığın gizemli gücü.",
                            IconEmoji = "🌑",
                            ImageUrl = "/images/frames/shadow.png",
                            Name = "Gece Lordu",
                            PriceInStones = 700,
                            RequiredBookCount = 50
                        },
                        new
                        {
                            Id = 10,
                            Description = "Yıldız tozuyla bezeli prestij.",
                            IconEmoji = "💎",
                            ImageUrl = "/images/frames/diamond.png",
                            Name = "Elmas Pırıltısı",
                            PriceInStones = 1000,
                            RequiredBookCount = 75
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dönen nebulalar ve yıldız tarlası.",
                            IconEmoji = "🌌",
                            ImageUrl = "/images/frames/galaxy.png",
                            Name = "Derin Uzay",
                            PriceInStones = 1250,
                            RequiredBookCount = 100
                        },
                        new
                        {
                            Id = 12,
                            Description = "Tüm spektruma hükmedenlerin çerçevesi.",
                            IconEmoji = "🌈",
                            ImageUrl = "/images/frames/rainbow.png",
                            Name = "Efsanevi Prizma",
                            PriceInStones = 2000,
                            RequiredBookCount = 150
                        });
                });

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveFrameImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRewardClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyPagesRead")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyReadingGoal")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StreakFreezes")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WisdomStones")
                        .HasColumnType("int");

                    b.Property<int>("YearlyReadingGoal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.UserFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileFrameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileFrameId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFrames");
                });

            modelBuilder.Entity("BookManagementApp.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RewardStones")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Okuma",
                            ColorHex = "#cd7f32",
                            Description = "İlk kitabınızı okudunuz.",
                            IconClass = "fa-book-open",
                            Name = "İlk Adım",
                            RewardStones = 10,
                            TargetValue = 1,
                            Tier = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Okuma",
                            ColorHex = "#c0c0c0",
                            Description = "10 kitap okudunuz.",
                            IconClass = "fa-book",
                            Name = "Kitap Sever",
                            RewardStones = 50,
                            TargetValue = 10,
                            Tier = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Okuma",
                            ColorHex = "#ffd700",
                            Description = "50 kitap okudunuz.",
                            IconClass = "fa-layer-group",
                            Name = "Kütüphaneci",
                            RewardStones = 150,
                            TargetValue = 50,
                            Tier = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Okuma",
                            ColorHex = "#e5e4e2",
                            Description = "100 kitap okudunuz.",
                            IconClass = "fa-book-journal-whills",
                            Name = "Kitap Kurdu",
                            RewardStones = 500,
                            TargetValue = 100,
                            Tier = 4
                        },
                        new
                        {
                            Id = 24,
                            Category = "Okuma",
                            ColorHex = "#b9f2ff",
                            Description = "250 kitap okudunuz.",
                            IconClass = "fa-book-bookmark",
                            Name = "Raf Fatihi",
                            RewardStones = 1000,
                            TargetValue = 250,
                            Tier = 5
                        },
                        new
                        {
                            Id = 5,
                            Category = "Okuma",
                            ColorHex = "#c084fc",
                            Description = "500 kitap okudunuz.",
                            IconClass = "fa-book-atlas",
                            Name = "Okuma Üstadı",
                            RewardStones = 2000,
                            TargetValue = 500,
                            Tier = 6
                        },
                        new
                        {
                            Id = 6,
                            Category = "Odaklanma",
                            ColorHex = "#cd7f32",
                            Description = "İlk pomodoro seansınızı tamamladınız.",
                            IconClass = "fa-stopwatch",
                            Name = "Odak Çırağı",
                            RewardStones = 10,
                            TargetValue = 1,
                            Tier = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Odaklanma",
                            ColorHex = "#c0c0c0",
                            Description = "25 pomodoro seansı tamamladınız.",
                            IconClass = "fa-hourglass-half",
                            Name = "Zaman Bekçisi",
                            RewardStones = 50,
                            TargetValue = 25,
                            Tier = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Odaklanma",
                            ColorHex = "#ffd700",
                            Description = "100 pomodoro seansı tamamladınız.",
                            IconClass = "fa-hourglass-end",
                            Name = "Zamanın Hakimi",
                            RewardStones = 250,
                            TargetValue = 100,
                            Tier = 3
                        },
                        new
                        {
                            Id = 9,
                            Category = "Odaklanma",
                            ColorHex = "#e5e4e2",
                            Description = "500 pomodoro seansı tamamladınız.",
                            IconClass = "fa-brain",
                            Name = "Odaklanma Ustası",
                            RewardStones = 1000,
                            TargetValue = 500,
                            Tier = 4
                        },
                        new
                        {
                            Id = 25,
                            Category = "Odaklanma",
                            ColorHex = "#b9f2ff",
                            Description = "1000 pomodoro seansı tamamladınız.",
                            IconClass = "fa-meteor",
                            Name = "Derin Odak",
                            RewardStones = 2000,
                            TargetValue = 1000,
                            Tier = 5
                        },
                        new
                        {
                            Id = 26,
                            Category = "Odaklanma",
                            ColorHex = "#c084fc",
                            Description = "2500 pomodoro seansı tamamladınız.",
                            IconClass = "fa-infinity",
                            Name = "Zamanın Efsanesi",
                            RewardStones = 5000,
                            TargetValue = 2500,
                            Tier = 6
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sosyal",
                            ColorHex = "#cd7f32",
                            Description = "İlk takip işleminizi gerçekleştirdiniz.",
                            IconClass = "fa-user-plus",
                            Name = "Merhaba Dünya",
                            RewardStones = 10,
                            TargetValue = 1,
                            Tier = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "Sosyal",
                            ColorHex = "#c0c0c0",
                            Description = "10 kullanıcıyı takip ettiniz.",
                            IconClass = "fa-users",
                            Name = "Sosyalleşen",
                            RewardStones = 40,
                            TargetValue = 10,
                            Tier = 2
                        },
                        new
                        {
                            Id = 12,
                            Category = "Sosyal",
                            ColorHex = "#ffd700",
                            Description = "50 kullanıcıyı takip ettiniz.",
                            IconClass = "fa-people-group",
                            Name = "Çevresi Geniş",
                            RewardStones = 100,
                            TargetValue = 50,
                            Tier = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "Sosyal",
                            ColorHex = "#e5e4e2",
                            Description = "100 kullanıcıyı takip ettiniz.",
                            IconClass = "fa-star",
                            Name = "Fenomen",
                            RewardStones = 500,
                            TargetValue = 100,
                            Tier = 4
                        },
                        new
                        {
                            Id = 27,
                            Category = "Sosyal",
                            ColorHex = "#b9f2ff",
                            Description = "250 kullanıcıyı takip ettiniz.",
                            IconClass = "fa-handshake",
                            Name = "Topluluk Yıldızı",
                            RewardStones = 1000,
                            TargetValue = 250,
                            Tier = 5
                        },
                        new
                        {
                            Id = 28,
                            Category = "Sosyal",
                            ColorHex = "#c084fc",
                            Description = "500 kullanıcıyı takip ettiniz.",
                            IconClass = "fa-heart",
                            Name = "Kitap Kulübü Efsanesi",
                            RewardStones = 2500,
                            TargetValue = 500,
                            Tier = 6
                        },
                        new
                        {
                            Id = 14,
                            Category = "Etkileşim",
                            ColorHex = "#cd7f32",
                            Description = "İlk kitap yorumunuzu yaptınız.",
                            IconClass = "fa-comment",
                            Name = "İlk Bakış",
                            RewardStones = 15,
                            TargetValue = 1,
                            Tier = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Etkileşim",
                            ColorHex = "#c0c0c0",
                            Description = "10 kitap yorumu yaptınız.",
                            IconClass = "fa-comments",
                            Name = "Eleştirmen",
                            RewardStones = 75,
                            TargetValue = 10,
                            Tier = 2
                        },
                        new
                        {
                            Id = 16,
                            Category = "Etkileşim",
                            ColorHex = "#ffd700",
                            Description = "50 kitap yorumu yaptınız.",
                            IconClass = "fa-pen-fancy",
                            Name = "Uzman Yazar",
                            RewardStones = 200,
                            TargetValue = 50,
                            Tier = 3
                        },
                        new
                        {
                            Id = 17,
                            Category = "Etkileşim",
                            ColorHex = "#e5e4e2",
                            Description = "100 kitap yorumu yaptınız.",
                            IconClass = "fa-magnifying-glass-chart",
                            Name = "Edebiyat Dedektifi",
                            RewardStones = 500,
                            TargetValue = 100,
                            Tier = 4
                        },
                        new
                        {
                            Id = 29,
                            Category = "Etkileşim",
                            ColorHex = "#b9f2ff",
                            Description = "250 kitap yorumu yaptınız.",
                            IconClass = "fa-feather",
                            Name = "Kalem Ustası",
                            RewardStones = 1000,
                            TargetValue = 250,
                            Tier = 5
                        },
                        new
                        {
                            Id = 30,
                            Category = "Etkileşim",
                            ColorHex = "#c084fc",
                            Description = "500 kitap yorumu yaptınız.",
                            IconClass = "fa-scroll",
                            Name = "Edebiyatın Sesi",
                            RewardStones = 2500,
                            TargetValue = 500,
                            Tier = 6
                        },
                        new
                        {
                            Id = 18,
                            Category = "Bilgelik",
                            ColorHex = "#cd7f32",
                            Description = "100 Bilgelik taşı topladınız.",
                            IconClass = "fa-gem",
                            Name = "Çaylak",
                            RewardStones = 0,
                            TargetValue = 100,
                            Tier = 1
                        },
                        new
                        {
                            Id = 19,
                            Category = "Bilgelik",
                            ColorHex = "#c0c0c0",
                            Description = "1000 Bilgelik taşı topladınız.",
                            IconClass = "fa-medal",
                            Name = "Bilge Kişi",
                            RewardStones = 0,
                            TargetValue = 1000,
                            Tier = 2
                        },
                        new
                        {
                            Id = 20,
                            Category = "Bilgelik",
                            ColorHex = "#ffd700",
                            Description = "5000 Bilgelik taşı topladınız.",
                            IconClass = "fa-crown",
                            Name = "Aydınlanmış",
                            RewardStones = 0,
                            TargetValue = 5000,
                            Tier = 3
                        },
                        new
                        {
                            Id = 21,
                            Category = "Bilgelik",
                            ColorHex = "#e5e4e2",
                            Description = "10000 Bilgelik taşı topladınız.",
                            IconClass = "fa-chess-king",
                            Name = "Bilgeliğin Efendisi",
                            RewardStones = 0,
                            TargetValue = 10000,
                            Tier = 4
                        },
                        new
                        {
                            Id = 31,
                            Category = "Bilgelik",
                            ColorHex = "#b9f2ff",
                            Description = "25000 Bilgelik taşı topladınız.",
                            IconClass = "fa-coins",
                            Name = "Hazine Avcısı",
                            RewardStones = 0,
                            TargetValue = 25000,
                            Tier = 5
                        },
                        new
                        {
                            Id = 32,
                            Category = "Bilgelik",
                            ColorHex = "#c084fc",
                            Description = "50000 Bilgelik taşı topladınız.",
                            IconClass = "fa-hat-wizard",
                            Name = "Ebedi Bilge",
                            RewardStones = 0,
                            TargetValue = 50000,
                            Tier = 6
                        },
                        new
                        {
                            Id = 33,
                            Category = "İstikrar",
                            ColorHex = "#cd7f32",
                            Description = "3 gün üst üste uygulamayı kullandınız.",
                            IconClass = "fa-bolt",
                            Name = "İlk Kıvılcım",
                            RewardStones = 25,
                            TargetValue = 3,
                            Tier = 1
                        },
                        new
                        {
                            Id = 22,
                            Category = "İstikrar",
                            ColorHex = "#c0c0c0",
                            Description = "7 gün üst üste uygulamayı kullandınız.",
                            IconClass = "fa-calendar-check",
                            Name = "İstikrarlı",
                            RewardStones = 100,
                            TargetValue = 7,
                            Tier = 2
                        },
                        new
                        {
                            Id = 23,
                            Category = "İstikrar",
                            ColorHex = "#ffd700",
                            Description = "30 gün üst üste uygulamayı kullandınız.",
                            IconClass = "fa-fire",
                            Name = "Demir Disiplin",
                            RewardStones = 500,
                            TargetValue = 30,
                            Tier = 3
                        },
                        new
                        {
                            Id = 34,
                            Category = "İstikrar",
                            ColorHex = "#e5e4e2",
                            Description = "100 gün üst üste uygulamayı kullandınız.",
                            IconClass = "fa-shield-halved",
                            Name = "Sarsılmaz",
                            RewardStones = 1500,
                            TargetValue = 100,
                            Tier = 4
                        },
                        new
                        {
                            Id = 35,
                            Category = "İstikrar",
                            ColorHex = "#b9f2ff",
                            Description = "180 gün üst üste uygulamayı kullandınız.",
                            IconClass = "fa-mountain",
                            Name = "Adanmış Okur",
                            RewardStones = 3000,
                            TargetValue = 180,
                            Tier = 5
                        },
                        new
                        {
                            Id = 36,
                            Category = "İstikrar",
                            ColorHex = "#c084fc",
                            Description = "365 gün üst üste uygulamayı kullandınız.",
                            IconClass = "fa-trophy",
                            Name = "Bir Yılın Hikayesi",
                            RewardStones = 10000,
                            TargetValue = 365,
                            Tier = 6
                        });
                });

            modelBuilder.Entity("BookManagementApp.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockedId")
                        .HasColumnType("int");

                    b.Property<int>("BlockerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlockedId");

                    b.HasIndex("BlockerId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("BookManagementApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookManagementApp.Models.BookComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookComments");
                });

            modelBuilder.Entity("BookManagementApp.Models.BookExcerpt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookAuthor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookExcerpts");
                });

            modelBuilder.Entity("BookManagementApp.Models.BookLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookLikes");
                });

            modelBuilder.Entity("BookManagementApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookManagementApp.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("BookManagementApp.Models.ExcerptReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ExcerptId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExcerptId", "UserId")
                        .IsUnique();

                    b.ToTable("ExcerptReactions");
                });

            modelBuilder.Entity("BookManagementApp.Models.ExcerptReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExcerptId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("ExcerptReports");
                });

            modelBuilder.Entity("BookManagementApp.Models.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("FollowingId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("BookManagementApp.Models.ProfileAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceInStones")
                        .HasColumnType("int");

                    b.Property<int>("RequiredBookCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProfileAvatars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/3906/3906607.png",
                            Name = "Klasik Prens",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/4042/4042356.png",
                            Name = "Klasik Prenses",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/523/523461.png",
                            Name = "Sevimli Ninja",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/4086/4086679.png",
                            Name = "Bilge Baykuş",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/4042/4042422.png",
                            Name = "Kitap Kurdu 1",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/4086/4086577.png",
                            Name = "Gözlüklü Bilgin",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/189/189162.png",
                            Name = "Şapkalı Büyücü",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/4322/4322991.png",
                            Name = "Gizemli Okur",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/4140/4140047.png",
                            Name = "Genç Öğrenci",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/8854/8854242.png",
                            Name = "Mutlu Çocuk",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/17715/17715285.png",
                            Name = "Kedi Dostu",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/8231/8231329.png",
                            Name = "Sevimli Köpek",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/1326/1326377.png",
                            Name = "Uzaylı Okuyucu",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/9308/9308979.png",
                            Name = "Robot Kitapkurdu",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/780/780258.png",
                            Name = "Canavar Okur",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Başlangıç Avatarı",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/624/624150.png",
                            Name = "Sevimli Hayalet",
                            PriceInStones = 0,
                            RequiredBookCount = 0
                        });
                });

            modelBuilder.Entity("BookManagementApp.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BookManagementApp.Models.StorePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceInStones")
                        .HasColumnType("int");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StorePackages");
                });

            modelBuilder.Entity("BookManagementApp.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("BookManagementApp.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("BookManagementApp.Models.UserAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileAvatarId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileAvatarId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAvatars");
                });

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.Contact", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.UserFrame", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.ProfileFrame", "ProfileFrame")
                        .WithMany()
                        .HasForeignKey("ProfileFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileFrame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.Block", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("BookManagementApp.Models.Book", b =>
                {
                    b.HasOne("BookManagementApp.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.BookComment", b =>
                {
                    b.HasOne("BookManagementApp.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.BookExcerpt", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.BookLike", b =>
                {
                    b.HasOne("BookManagementApp.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.Category", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.ChatMessage", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BookManagementApp.Models.ExcerptReaction", b =>
                {
                    b.HasOne("BookManagementApp.Models.BookExcerpt", "Excerpt")
                        .WithMany()
                        .HasForeignKey("ExcerptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Excerpt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.ExcerptReport", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("BookManagementApp.Models.Follow", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Following")
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("BookManagementApp.Models.Report", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("BookManagementApp.Models.StudySession", b =>
                {
                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.UserAchievement", b =>
                {
                    b.HasOne("BookManagementApp.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Models.UserAvatar", b =>
                {
                    b.HasOne("BookManagementApp.Models.ProfileAvatar", "ProfileAvatar")
                        .WithMany()
                        .HasForeignKey("ProfileAvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementApp.Areas.Admin.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileAvatar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookManagementApp.Areas.Admin.Models.User", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Categories");

                    b.Navigation("Contacts");

                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("BookManagementApp.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
